packageExtensions:
  "@docusaurus/mdx-loader@*":
    dependencies:
      react: "*"
  "@docusaurus/core@*":
    dependencies:
      "@docusaurus/preset-classic": ^2.0.0-alpha.59
  "@docusaurus/plugin-content-docs@*":
    dependencies:
      chalk: "*"
      lodash: "*"
  "@docusaurus/preset-classic@*":
    dependencies:
      "@docusaurus/utils": ^2.0.0-alpha.59
  react-loadable-ssr-addon@*:
    dependencies:
      "@babel/runtime": "*"

yarnPath: .yarn/releases/yarn-2.1.1.js
