packageExtensions:
  "@docusaurus/mdx-loader@*":
    dependencies:
      react: "*"
  "@docusaurus/preset-classic@*":
    dependencies:
      "@docusaurus/utils": ^2.0.0-alpha.56
  "@docusaurus/theme-classic@*":
    dependencies:
      core-js: "*"

yarnPath: .yarn/releases/yarn-2.1.1.js
